### ISSUE TITLE
value schemas from package plugin has missing keys

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#1069]
**Bug description**

When user uses `tanzu package available get <name> --values-schema`, there has some keys missing from the output.

If users has the following schema defined in the package, `accelerator` will be ignored from above command.
```
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        accelerator:
          additionalProperties: true
          description: Accelerator configuration
          properties: {}
          type: object
      type: object
```

The root causes of this issue are:

- schema parser recursively looks into nested `properties` and does not return immediately when hits empty `properties`
- the return happens when function exits without adding the key(`accelerator`) into final result.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

`tanzu package available get <name> --values-schema` returns all the keys defined in schema.

**Steps to reproduce the bug**

- Use the schema from above as an example to create a package for testing.
- Run `tanzu package available get <name> --values-schema`, the key will be ignored.

**Version** (include the SHA if the version is not obvious)

- da92b57eb7b9a893519503b6438bf59997212a27

**Environment where the bug was observed (cloud, OS, etc)**

- Mac OS

**Relevant Debug Output (Logs, manifests, etc)**
