### ISSUE TITLE
FeatureGates package installation fails to create tanzu-featuregates-manager-clusterrole

### ISSUE THREAD

**Issue by yharish991** [vmware-tanzu/tanzu-framework#1079]
**Bug description**
Sometimes Featuregates package installation fails with the below error in the PackageInstall CR status
```
status:
    conditions:
    - message: Error (see .status.usefulErrorMessage for details)
      status: "True"
      type: ReconcileFailed
    friendlyDescription: 'Reconcile failed: Error (see .status.usefulErrorMessage
      for details)'
    lastAttemptedVersion: 0.10.0-dev
    observedGeneration: 3
    usefulErrorMessage: |-
      I1104 17:46:49.205536     491 request.go:665] Waited for 1.0230436s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/config.tanzu.vmware.com/v1alpha1?timeout=32s
      I1104 17:46:59.173390     491 request.go:665] Waited for 6.9974612s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/policy/v1beta1/namespaces/default/poddisruptionbudgets?labelSelector=kapp.k14s.io%2Fapp%3D1636047645907196100
      I1104 17:47:09.173585     491 request.go:665] Waited for 15.3974388s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/discovery.k8s.io/v1beta1/namespaces/cert-manager/endpointslices?labelSelector=kapp.k14s.io%2Fapp%3D1636047645907196100
      I1104 17:47:19.223088     491 request.go:665] Waited for 23.396621s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/kappctrl.k14s.io/v1alpha1/namespaces/default/apps?labelSelector=kapp.k14s.io%2Fapp%3D1636047645907196100
      kapp: Error: Applying create clusterrolebinding/tanzu-featuregates-manager-clusterrolebinding (rbac.authorization.k8s.io/v1) cluster:
        Creating resource clusterrolebinding/tanzu-featuregates-manager-clusterrolebinding (rbac.authorization.k8s.io/v1) cluster: clusterroles.rbac.authorization.k8s.io "tanzu-featuregates-manager-clusterrole" not found (reason: NotFound)
    version: 0.10.0-dev
```

We need to make sure the resources are created in proper order to avoid above problem and this can be done by applying ordering using kapp buitin rules (https://carvel.dev/kapp/docs/latest/apply-ordering/)

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

When FeatureGates package is installed, it should create the resources that are part of the Package in a particular order.

**Steps to reproduce the bug**
1. Generate Package bundle
PACKAGE_REPOSITORY=management PACKAGE_NAME=featuregates make package-bundle
2. Generate Package Repo bundle
PACKAGE_REPOSITORY=management PACKAGE_NAME=core-management-cliplugins make package-bundle
3. Push Package bundle
OCI_REGISTRY=${OCI_REGISTRY} make push-package-bundles
4. Push Package Repo bundle
OCI_REGISTRY=${OCI_REGISTRY} make push-package-repo-bundles
5. Install kapp-controller [v0.28.0](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.28.0)
6. Create PackageRepository CR with the above generated package repo bundle
7. Create ServiceAccount for PackageInstall CR
````
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-featuregates-package-sa
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-featuregates-package-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - featuregates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - featuregates/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - features
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - features/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-featuregates-package-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-featuregates-package-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-featuregates-package-sa
    namespace: tkg-system
````
8. Create PackageInstall CR
```
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-featuregates
  namespace: tkg-system
spec:
  packageRef:
    refName: featuregates.tanzu.vmware.com
    versionSelection:
      prereleases: {}
  serviceAccountName: tanzu-featuregates-package-sa
```
9. Inspect PackageInstall CR status
```
$ kubectl get packageinstalls.packaging.carvel.dev tanzu-featuregates -n tkg-system -o jsonpath="Status: {.status}"
```

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
