### ISSUE TITLE
Handle backslash in values returning ytt error

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/tanzu-framework#1254]
**Bug description**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [x] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Expected behavior**
TAP profiles with registry or tanzunet passwords which can contain `\` are being parsed as escape characters by ytt.

**Steps to reproduce the bug**
Run the command below with `\` inside the tap-values.yml file.

```
tanzu package install tap -p tap.tanzu.vmware.com -v 0.3.0 --values-file tap-values.yml -n tap-install
```

**Version** (include the SHA if the version is not obvious)
```
version: v0.10.0
buildDate: 2021-11-03
sha: fd96bebe
```

**Environment where the bug was observed (cloud, OS, etc)**
n/a

**Relevant Debug Output (Logs, manifests, etc)**
```
| Installing package 'tap.tanzu.vmware.com' 

| Getting package install for 'tap' 
| Getting package metadata for 'tap.tanzu.vmware.com' 
| Updating secret 'tap-tap-install-values' 
| Updating package install for 'tap' 
/ Waiting for 'PackageInstall' reconciliation for 'tap' 


Error: resource reconciliation failed: ytt: Error: Extracting data value from file:
  Unmarshaling YAML data values file '/etc/kappctrl-mem-tmp/kapp-controller-template-values3180492965/tap-values.yml': yaml: line 6: found unknown escape character
. Reconcile failed: Error (see .status.usefulErrorMessage for details)
Error: exit status 1
```

**Comment by blc1996** [comment]
Hi @GuessWhoSamFoo , could you share the content of `tap-values.yml ` that you are using?

**Comment by GuessWhoSamFoo** [comment]
In this example, it would be `kp_default_respository_password` causing problems

```
profile: dev-light

buildservice:
  kp_default_repository: "index.docker.io/sfoo/build-service"
  kp_default_repository_username: "sfoo"
  kp_default_repository_password: "example_\_with_backslash"
  tanzunet_username: "foos@vmware.com"
  tanzunet_password: "password"

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "https://index.docker.io/v1/"
    repository: "sfoo"

learningcenter:
  ingressDomain: "example.com"

tap_gui:
  service_type: LoadBalancer

cnrs:
  provider: local
```
