### ISSUE TITLE
PoC: TKR Resolver: infra-Machine webhook: how should we install this for each infra provider?

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#1334]
To inject the resolved image data into infra-Machine objects (e.g. AWSMachine) we need a mutating (onCreate) webhook for each infra-Machine type that we support. The webhook will take the `run.tanzu.vmware.com/os-image-ref` annotation data and set the appropriate fields in the infra-Machine object being created. 

For example, let's suppose, AWSMachine has the following annotation in its metadata:

```yaml
metadata:
  annotations:
    run.tanzu.vmware.com/os-image-ref: |
      id: ami-0f2e5eec7ae0a1986
      partition: aws
      region: ap-northeast-1
```

The webhook will need to set AWSMachine `spec.ami.id := ami-0f2e5eec7ae0a1986`

The webhook is trivial for each specific provider. What we need to figure out by doing this PoC is: where does this implementation live? What needs to be done to make sure it's installed with the infrastructure provider onto the management cluster?

**Comment by prkalle** [comment]
PoC was done for AWS provider and verified that 
1) If the below annotation is added in cluster.spec.controlPlane.metadata.annotations 
```
        metadata:
          annotations:
            run.tanzu.vmware.com/os-image-ref: |
              id: ami-0f2e5eec7ae0a1986
``` 
It is being populated to AWSMachine objects and the mutating webhook implemented in the PoC would access this annotation and it did set the spec.ami.id=ami-0f2e5eec7ae0a1986. The cluster was created successfully.
2) The current plan is to have the uTKG code related to TKr in tanzu-framework under `tanzu-framework/pkg/v2/tkr/`. If there would be any new decision in futture regarding moving the TKr code to different repository, we can move the complete folder to new repository.
3) The webhook would be installed through carval package API.
