### ISSUE TITLE
TKR Resolver: Cluster webhook

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#1347]
Using the TKR resolution algorithm from #1346, implement CAPI Cluster mutating webhook, that would resolve the TKR and OSImages for the Cluster being created or updated.

To enable TKR resolution, ClusterClass objects must be annotated with run.tanzu.vmware.com/resolve-tkr: "<selector>" , for example:
run.tanzu.vmware.com/resolve-tkr: "corp.example.com/hardened=true" 

This annotation specifies the label selector which candidate TKRs MUST satisfy (in addition to being compatible with the management cluster and not deactivated). It is recommended (but not required) to set it to the same label query as the desired TKR .spec.updateConstraints  value. Empty value means all available TKRs will be in the candidate set. 

When a workload cluster is being created or updated, several modifications are made to Cluster API objects: 
* Kubernetes version and TKR should be resolved based on the above annotation and  Cluster.spec.topology.version. The following labels should be set on the Cluster object, with values referring to the resolved TKR and Kubernetes version, for example:
  * run.tanzu.vmware.com/tkr: v1.21.2---vmware.1-tkg.1 
  * run.tanzu.vmware.com/kubernetesVersion: v1.21.2---vmware.1
* OSmage objects should be resolved based on the run.tanzu.vmware.com/resolve-os-image: "<selector>" annotation set in the ClusterClass controlPlane and machineDeployment metadata  (using labels on OSImage and TKR objects):
run.tanzu.vmware.com/resolve-os-image: "os-name=ubuntu,os-version=20.04,os-arch=amd64,ami-region=ap-northeast-1"
* OSImage is resolved based on Kubernetes version and the provided label selector. image-type=<image-type> is implicitly added to the selector based on the type of infrastructure provider. For our example,
image-type=ami. 
The TKR shipping the OSImage MUST satisfy the selector from run.tanzu.vmware.com/resolve-tkr annotation. Resolved OSImage reference label is set in the metadata section of the Cluster topology controlPlane and machineDeployment sections:
  * run.tanzu.vmware.com/os-image: v1.21.2---vmware.1-tkg.1-ami-0f2e5eec7ae0a1986 

Here’s an example ClusterClass annotated to use the described behavior:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: my-clusterclass-1
  namespace: default
  annotations:
    run.tanzu.vmware.com/resolve-tkr: "corp.example.com/hardened=true"
spec:
  controlPlane:
    metadata:
      annotations:
        run.tanzu.vmware.com/resolve-os-image: "os-name=ubuntu,os-version=20.04,os-arch=amd64,ami-region=ap-northeast-1"
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: high-availability-kcp
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: ubuntu2004-aws-machine-template
  workers:
    deployments:
    - class: ubuntu-worker
      template:
        metadata:
      annotations:
        run.tanzu.vmware.com/resolve-os-image: "os-name=ubuntu,os-version=20.04,os-arch=amd64,ami-region=ap-northeast-1"
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: ubuntu-bootstrap
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
            name: ubuntu2004-aws-machine-template
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSClusterTemplate
      name: aws-cluster
  variables:
  - name: TKR_KUBERNETES_SPEC
    schema:
      openAPIV3Schema:
        type: object
```

Note the `TKR_KUBERNETES_SPEC` variable in the above ClusterClass example. It's schema is defined as `type: object`, which is open ended. This variable is expected to be populated by the TKR Resolver Cluster webhook with the value of `spec.kubernetes` of the resolved TKR.

### Example cluster creation flow
Let’s take the following Cluster example (referring to the above ClusterClass) as input:

```yaml 
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster-1
  namespace: default
spec:
  topology:
    class: my-clusterclass-1
    version: v1.21
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: ubuntu-worker
        name: ubuntu-workers
        replicas: 1
#   variables: ...
```

Given that the referred ClusterClass has run.tanzu.vmware.com/resolve-tkr: "corp.example.com/hardened=true" annotation, the TKR resolver webhook will lookup the latest available (compatible with the management cluster, not deactivated, with all necessary OSImages) TKR satisfying the label query from the annotation. Having found the TKR, it will set appropriate labels on the Cluster:
* run.tanzu.vmware.com/tkr: v1.21.2---vmware.1-tkg.1
* run.tanzu.vmware.com/kubernetesVersion: v1.21.2---vmware.1

These labels may seem redundant with spec.topology.version (which is the desired version). They are not: these are the resolved Kubernetes version and TKR. The desired Kubernetes version may not be available (as shipped by a TKR with the necessary OSImages). 

Example Cluster with TKR and OSImage resolution labels set:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster-1
  namespace: default
  labels:
    run.tanzu.vmware.com/tkr: v1.21.2---vmware.1-tkg.1
    run.tanzu.vmware.com/kubernetesVersion: v1.21.2---vmware.1
spec:
  topology:
    class: my-clusterclass-1
    version: v1.21
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/os-image-ref: |
            id: ami-0f2e5eec7ae0a1986
            partition: aws
            region: ap-northeast-1
        labels:
          run.tanzu.vmware.com/os-image: v1.21.2---vmware.1-tkg.1-ami-0f2e5eec7ae0a1986
      replicas: 1
    workers:
      machineDeployments:
      - metadata:
        annotations:
          run.tanzu.vmware.com/os-image-ref: |
            id: ami-0f2e5eec7ae0a1986
            partition: aws
            region: ap-northeast-1
          labels:
            run.tanzu.vmware.com/os-image: v1.21.2---vmware.1-tkg.1-ami-0f2e5eec7ae0a1986
        class: ubuntu-worker
        name: ubuntu-workers
        replicas: 1
    variables:
    - name: TKR_KUBERNETES_SPEC
      value:
        version: v1.21.2+vmware.1
        imageRepository: projects.registry.vmware.com/tkg
        etcd:
          imageTag: v3.5.0
        pause:
          imageTag: "3.4.1"
        coredns:
          imageTag: v1.8.0_vmware.5
#   - ...
```
