### ISSUE TITLE
TKR Source Controller: install TKRs from TKR packages

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#1352]
Carvel Package Management API is used for packaging and distribution of TKR API objects: each TKR with any related OSImages, bootstrap Packages and (possibly in the future) any other necessary objects is wrapped in a Carvel package. 

Zero or more TKR PackageRepository objects are placed in the tkg-system namespace. These PackageRepositories are the “source channels” for getting TKR Packages into the management cluster. 

Here’s how TKR packages are going to be structured:
* (TKR) PackageRepository in the tkg-system namespace:
  * (TKR) Packages with the following API resources:
    * TanzuKubernetesReleases
    * OSImages
    * Bootstrap Packages

A TKR Package object looks something like this:

```yaml
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tkr.tkg.vmware.com.1.21.2---vmware.1-tkg.1
  namespace: tkg-system
  labels:
    run.tanzu.vmware.com/tkrPackage: ""
spec:
  refName: tkr.tkg.vmware.com
  version: 1.21.2+vmware.1-tkg.1
  licenses:
  - "Apache 2.0"
  releasedAt: 2021-05-05T18:57:06Z
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tkg/packages/tkr@sha256:...
```

The run.tanzu.vmware.com/tkrPackage: "" label marks the package as a TKR package. Noticing this label, the TKR Controller immediately installs the package, which will create TKR, OSImages and bootstrap Packages.
