### ISSUE TITLE
Values schema documents all nodes of the configuration tree, not only leaf nodes

### ISSUE THREAD

**Issue by mamachanko** [vmware-tanzu/tanzu-framework#1528]
(This is used to request new product features)

**Describe the feature request**

A kapp-controller `Package` can hold a `spec.valueSchema.openAPIv3` object to document the configuration surface of the package. This schema can be inspected with

```shell
tanzu package available get <my-package>/<my-package-version> --namespace <installation-namespace> --values-schema
```

Let's say my package has the following configuration surface:
```yaml
greeting: Hello
person:
  first_name: Gunun
  last_name: Banan
```
and my package YAML contains an OpenAPI v3 schema for ever node:
```yaml
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: greetomatic.mamachanko.com.1.2.3
spec:
  refName: greetomatic.mamachanko.com
  version: 1.2.3
  valuesSchema:
    openAPIv3:
      type: object
      properties:
        greeting:
          type: string
          default: hello
          description: The greeting formula
        person:
          type: object
          additionalProperties: false
          description: The person to greet
          properties:
            first_name:
              type: string
              description: The person's first name
            last_name:
              type: string
              description: The person's last name
  template:
    # ...
```
Then only the leaf nodes will be documented by `tanzu ... --values-schema`:
 * `greeting`
 * `person.first_name`
 * `person.last_name`

The intermediate node `person` will not be document. It would be helpful though, because it's description says "the person to greet" which is important context when reading "the person's last name".

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
