### ISSUE TITLE
TKR infra-Machine webhooks (with packages)

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#1532]
Code to implement TKR infra-Machine webhooks AND package manifests to produce Carvel packages. We need such package for every infrastructure provider: aws, azure, docker, vsphere.

## Details
If the `run.tanzu.vmware.com/os-image-ref` annotation is present in the infra-Machine metadata, the webhook should populate the configured fields in the infra-Machine spec. 

For example, an AWSMachine object is being created and has the following in its metadata:
```yaml
  annotations:
    run.tanzu.vmware.com/os-image-ref: |
      id: ami-0f2e5eec7ae0a1986
``` 
The mutating webhook should read this annotation, and set 
`spec.ami.id := "ami-0f2e5eec7ae0a1986"` in the final AWSMachine object. 

The webhook should be installable as a Carvel package, so we need package manifests (package.yaml) for all infrastructure providers: aws, azure, docker, vsphere.
