### ISSUE TITLE
Capture triage data on cluster creation failure

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/tanzu-framework#1663]
**Describe the feature request**

During deployment, we capture the kubectl configuration and other details about
the bootstrap kind cluster and the cluster that is actively being deployed. We
use some of this to help guide the user today:

```txt
Failure while deploying management cluster, Here are some steps to investigate the cause:
Debug:
kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig /home/test/.kube-tkg/tmp/config_6SDG31q1
kubectl logs deployment.apps/ -n manager --kubeconfig /home/test/.kube-tkg/tmp/config_6SDG31q1
```

Since we have this information, we should actually perform some of the
debugging steps for the end user.

As a base requirement for this proposal, debug commands such as getting pod and
deployment status from the cluster should be run, with the output captured to
the bootstrap log. We should also capture the error logs from the CAPI provider
manager pod (assuming things have gotten that far) and include that in the
bootstrap log.

For the purposes of this request, the requirement is only to capture
this output so it can be used for later troubleshooting. But since we have this
information, a future effort of building in some parsing and automatic triaging
to the commands should be considered.

### Implementation Details/Notes/Constraints

* The main target for these changes are `management-cluster` and `cluster`
  create commands
* Output will be different between these two as there are different details
  that are more relevant for one versus the other
* The same output principles should be considered for things like `delete`
  commands and any others that perform a multi-step process to accomplish

With the debug functional requirement in mind, the following will be
implemented to capture to our bootstrap log. These are too detailed or verbose
to print to the console unless we can glean a clear summary failure message
from the output. All trace logging will be captured in the bootstrap log so we
have it available and can read through that log to get a full picture of the
failure condition of the cluster.

#### Cluster API Details

Both the `management-cluster` and `cluster` creation operations utilize
[cluster-api](https://cluster-api.sigs.k8s.io/) for declarative cluster creation.

Since we have the `kubeconfig` for the bootstrap and management clusters, we can
use this to gain more visibility into the cluster deployment process. We can get
the [Cluster](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html)
CRDs during deployment to inspect the Status.Conditions to get the status of
the new cluster creation. The JSON output from getting Cluster objects gives the
following:

```yaml
"status": {
      "conditions": [
        {
            "lastTransitionTime": "2022-01-31T20:29:39Z",
            "status": "True",
            "type": "Ready"
        },
        {
            "lastTransitionTime": "2022-01-31T20:29:29Z",
            "status": "True",
            "type": "ControlPlaneInitialized"
        },
        {
            "lastTransitionTime": "2022-01-31T20:29:39Z",
            "status": "True",
            "type": "ControlPlaneReady"
        },
        {
            "lastTransitionTime": "2022-01-31T20:28:50Z",
            "status": "True",
            "type": "InfrastructureReady"
        }
      ],
      "infrastructureReady": true,
      "observedGeneration": 2,
      "phase": "Provisioned"
  }
```

By inspecting each of these statuses, we can report the progress of the cluster
provisioning. In this case, we can use these summary statuses to update
progress on the command line in addition to capturing progress to the bootstrap
log.

Cluster-API also has `Bootstrap`, `Machine`, `MachineDeployment`, and other objects
that can be retrieved to find more details. We can explore the attributes of these
objects as well to see if there is any other status information to report to the
user.

Some of these Cluster-API objects will be too low level to show in the terminal
output at default verbosity, but we could get their details to include in the
bootstrap logging to aid in troubleshooting when deployments fail.

#### Cluster API Controller Logs

One common scenario we have found to work when troubleshooting deployment failures
is to [look at the `capX-controller-manager` POD logs](https://tanzucommunityedition.io/docs/latest/tsg-bootstrap/#troubleshooting-manually).
Looking for Error level logs (log lines that start with an `E`) will often indicate
what is failing in reconciliation that is preventing the cluster from being
properly created.

Again, with having access to the `kubeconfig` for the cluster, we are able to
automate this manual process, to some degree, by extracting these error logs
and capturing them in the bootstrap log for easier troubleshooting.

Another controller that provides relevant logs is the [Machine Healthcheck
Controller](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine-health-check.html)
(MHC). The MHC is responsible for checking on the health of machines. This
provides some good detail for failure conditions. Extracting logs from the MHC
could provide useful troubleshooting logs for TCE to capture in the bootstrap
logs and could help point to the source of deployment failures.

#### Kapp Controller Events

After the cluster has been initialized using Cluster-API, we perform additional
package configuration for a default set of packages. Failures are less common
after the cluster has been successfully deployed, but we can inspect the
kapp-controller logs or events to help diagnose any other failures.

**Describe alternatives you've considered**

We provide the end user some commands they can run to get more details, but we've found that often this doesn't get to the root of a failure, or only gives partial information that requires walking them through several other steps to get the full picture of the failure condition.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Additional context**
