### ISSUE TITLE
Cluster variables for proxy and custom certs

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#1772]
We have consensus on cluster vars for proxy and custom certs. These variables should replace whatever is being currently to set proxy and certificates in KappControllerConfig, VsphereCPIConfig and VsphereCSIConfig

```
    - name: proxy
      required: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            httpProxy:
              type: string
            httpsProxy:
              type: string
            noProxy:
              type: string
    - name: trust
      required: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            additionalTrustedCAs:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  data:
                    type: string
```
