### ISSUE TITLE
KappController API spec Deployment is missing a default

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#1887]
**Bug description**
Since https://github.com/vmware-tanzu/tanzu-framework/blob/main/apis/run/v1alpha3/kappcontrollerconfig_types.go#L33 is missing a default, a config created with params such as below will not result in kapp-controller running on a workload cluster
```
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: KappControllerConfig
metadata:
  name: v1.23.3---vmware.1-tkg.1
  namespace: tkg-system
spec:
  namespace: tkg-system
  kappController:
    createNamespace: false
    globalNamespace: tkg-system
```
**Affected product area (please put an X in all that apply)**

- [x] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Default config should work out of the box
