### ISSUE TITLE
Whitespace in OIDC scope configuration via installer UI not trimmed correctly

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu/tanzu-framework#1933]
**Bug description**

When running `tanzu management-cluster create --ui` there is a problem when entering a list of OIDC scopes, if the list contains spaces as well as commas. When used with Okta (at least) the requested scopes are seen to be invalid.

There is validation in [identity-step.component.ts](https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/identity-step/identity-step.component.ts) that the list of scopes entered is comma separated (and does not begin or end with whitespace). However, the comma-separated check in [validation.service.ts](https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/web/src/app/views/landing/wizard/shared/validation/validation.service.ts) does allow single spaces in addition to the commas:

```typescript
    /**
     * @method isCommaSeperatedList
     */
    isCommaSeperatedList(): any {
        return (control: AbstractControl) => {
            const ctrlValue: string = control.value;
            if (ctrlValue) {
                if (!XRegExp('^(((\\w+)(,\\s?\\w+)+)|(\\w+))$').test(ctrlValue)) {
                    return {
                        [ValidatorEnum.COMMA_SEPARATED_WORDS]: true
                    };
                }
            }
        }
    }
```

This means that when the Pinniped configuration YAML is finally generated, the value for `upstream_oidc_additional_scopes` has list items preceded by spaces:

```yaml
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: aws
tkg_cluster_role: management
custom_cluster_issuer: ""
custom_tls_secret: ""
http_proxy: ""
https_proxy: ""
no_proxy: ""
identity_management_type: oidc
pinniped:
  cert_duration: 2160h
  cert_renew_before: 360h
  supervisor_svc_endpoint: https://0.0.0.0:31234
  supervisor_ca_bundle_data: ca_bundle_data_of_supervisor_svc
  supervisor_svc_external_ip: 0.0.0.0
  supervisor_svc_external_dns: null
  upstream_oidc_client_id: <client-id>
  upstream_oidc_client_secret: <client-secret>
  upstream_oidc_issuer_url: <issuer-url>
  upstream_oidc_tls_ca_data: ""
  upstream_oidc_additional_scopes:
  - openId
  - ' profile'
  - ' email'
  - ' offline_access'
  - ' groups'
  upstream_oidc_claims:
    username: email
    groups: groups
  supervisor:
    service:
      name: pinniped-supervisor
      type: LoadBalancer
```

This caused OIDC operations to fail when used with an Okta development account with "custom scopes are not allowed for this request".

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [X] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

Whitespace should be stripped from OIDC scopes

**Steps to reproduce the bug**

Enter a comma-space separated list into the TKG cluster creation UI.

**Version** (include the SHA if the version is not obvious)

```
version: v1.4.2
buildDate: 2022-02-01
sha: 0732f1da
```

**Environment where the bug was observed (cloud, OS, etc)**

AWS

**Relevant Debug Output (Logs, manifests, etc)**
