### ISSUE TITLE
Add addons-manager package to TKG composite package

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#1947]
Add addons-manager package to TKG composite package

Default config for addons-manager needs to work out of the box for supervisor

```
hostNetwork: true
nodeSelector:
   node-role.kubernetes.io/master: ""
tolerations:
   - effect: NoSchedule
     key: node-role.kubernetes.io/master
     operator: Exists
   - key: CriticalAddonsOnly
     operator: Exists
   - effect: NoExecute
     key: node.alpha.kubernetes.io/notReady
     operator: Exists
   - effect: NoExecute
     key: node.alpha.kubernetes.io/unreachable
     operator: Exists
   - effect: NoSchedule
     key: kubeadmNode
     operator: Equal
     value: master

```
