### ISSUE TITLE
Store TKR Resolution results in Cluster variables

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#1993]
Add a ClusterClass variable named `TKR_DATA`. The value of this variable will contain a mapping from Kubernetes version strings (resolved values of `spec.topology.version`) to a map containing the data from the resolved TKR and OSImage:

```yaml
v1.22.3+vmware.1:
  kubernetesSpec:
    version: v1.22.3+vmware.1
    imageRepository: projects-stg.registry.vmware.com/tkg
    etcd:
      imageTag:  v3.5.0_vmware.7
    pause:
      imageTag: "3.5"
    coredns:
      imageTag: v1.8.4_vmware.7
    kube-vip:
      imageTag: v0.4.2_vmware.7
  osImageRef:
    id: ami-0f2e5eec7ae0a1986
    region: ap-northeast-1
  labels:
    run.tanzu.vmware.com/tkr: v1.22.3---vmware.1-tkg.1
    run.tanzu.vmware.com/os-image: v1.22.3---vmware.1-tkg.1-ami-0f2e5eec7ae0a1986
    os-type: linux
    os-name: ubuntu
    os-version: "20.04"
    os-arch: amd64
    image-type: ami
    ami-id: ami-0f2e5eec7ae0a1986
    ami-region: ap-northeast-1
v1.22.4+vmware.1:
  kubernetesSpec:
    version: v1.22.4+vmware.1
    imageRepository: projects-stg.registry.vmware.com/tkg
    etcd:
      imageTag:  v3.5.0_vmware.7
    pause:
      imageTag: "3.5"
    coredns:
      imageTag: v1.8.4_vmware.7
    kube-vip:
      imageTag: v0.4.2_vmware.7
  osImageRef:
    id: ami-0a3d6eac8ae0a2387
    region: ap-northeast-1
  labels:
    run.tanzu.vmware.com/tkr: v1.22.4---vmware.1-tkg.1
    run.tanzu.vmware.com/os-image: v1.22.4---vmware.1-tkg.1-ami-0a3d6eac8ae0a2387
    os-type: linux
    os-name: ubuntu
    os-version: "20.04"
    os-arch: amd64
    image-type: ami
    ami-id: ami-0a3d6eac8ae0a2387
    ami-region: ap-northeast-1
```
