### ISSUE TITLE
vsphereCPIConfigController includes non-paravirt datavalues for paravirt package

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#2192]
**Bug description**
vsphereCPIConfig controller is including both paravirt and non-paravirt datavalues even if they are not applicable and empty leading to package install failure

Example data value created
```
vsphereCPI:
    mode: vsphereParavirtualCPI
    tlsThumbprint: ""
    server: ""
    datacenter: ""
    username: ""
    password: ""
    region: ""
    zone: ""
    insecureFlag: false
    ipFamily: ""
    vmInternalNetwork: ""
    vmExternalNetwork: ""
    vmExcludeInternalNetworkSubnetCidr: ""
    vmExcludeExternalNetworkSubnetCidr: ""
    cloudProviderExtraArgs:
        tls-cipher-suites: ""
    nsxt:
        podRoutingEnabled: false
        routes:
            routerPath: ""
            clusterCidr: ""
        username: ""
        password: ""
        host: ""
        insecureFlag: false
        remoteAuth: false
        vmcAccessToken: ""
        vmcAuthHost: ""
        clientCertKeyData: ""
        clientCertData: ""
        rootCAData: ""
        secretName: ""
        secretNamespace: ""
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
    clusterAPIVersion: cluster.x-k8s.io/v1beta1
    clusterKind: Cluster
    clusterName: clusterclass-3
    clusterUID: f0fa4841-86f2-4ae8-b75b-0992f16c6814
    supervisorMasterEndpointIP: supervisor.default.svc
    supervisorMasterPort: "6443"
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Include only relevant config for package configuration
