### ISSUE TITLE
Configure cluster control-plane and worker nodes with custom nameservers on vSphere

### ISSUE THREAD

**Issue by christianang** [vmware-tanzu/tanzu-framework#238]
**Describe the feature request**

As a cluster operator, I would like to configure different DNS servers per cluster on vSphere. I would also like to be able to configure the control-plane node's DNS servers independently from the DNS servers on the worker nodes. I would like to configure this via a data value in my cluster's configuration file.

This is currently only scoped to vSphere because each cluster-api provider will have a different way to configure nameservers on their nodes. We can add support for other IaaSes after vSphere. Additionally, I haven't investigated if all providers allow you to configure nameservers through their cluster-api provider API so there may be additional work that needs to be done on providers to make this work for all IaaSes.

**Design/Acceptance**

Given I set `WORKER_NODE_NAMESERVERS` to the IP of my nameserver(s) in cluster configuration yaml
And I create the cluster on vSphere using `tanzu cluster create my-cluster -f ./my-configuration.yaml`
When I ssh onto the worker node and I `resolvectl` status
Then I see my nameserver(s) in the list of dns servers.

Given I set `CONTROL_PLANE_NODE_NAMESERVERS` to the IP of my nameserver(s) in cluster configuration yaml
And I create the cluster on vSphere using `tanzu cluster create my-cluster -f ./my-configuration.yaml`
When I ssh onto the control-plane node and I `resolvectl` status
Then I see my nameserver(s) in the list of dns servers.

Given I see either `WORKER_NODE_NAMESERVERS` or `CONTROL_PLANE_NODE_NAMESERVERS` set, but I am not using vSphere
When I run `tanzu cluster create my-cluster -f ./my-configuration.yaml`
Then I see a ytt template validation error

(I should also be able to do all the above using `tanzu management-cluster create` as well)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [X] Docs
- [ ] Installation
- [X] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Additional context**

For reference, when we start work on this, we can accomplish this by using something similar to the following overlay:

```yaml
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#! This is for control plane nodes. `-control-plane` can be replaced by `-worker` for worker nodes.
#@overlay/match by=overlay.subset({"kind":"VSphereMachineTemplate", "metadata": {"name": data.values.CLUSTER_NAME+"-control-plane"}})
---
spec:
  template:
    spec:
      network:
        devices:
        #@overlay/match by=overlay.all, expects="1+"
        -
          #@overlay/match missing_ok=True
          nameservers: ["1.2.3.4"]
```
