### ISSUE TITLE
TC07: AWS Cluster - Able to create/delete CC Guest cluster on AWS and verify if all addons are successfully deployed

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#2456]
Complete two parts:
- [x] Create/delete ClusterClass guest cluster on AWS
- [ ] Verify the following addons packages are successfully deployed:
   - CNI: antrea.tanzu.vmware.com
   - Kapp: kapp-controller.tanzu.vmware.com
   - AddittionalPackages: metrics-server.tanzu.vmware.com
   - AddittionalPackages: secretgen-controller.tanzu.vmware.com
   - AddittionalPackages: pinniped.tanzu.vmware.com

Addons are listed at https://github.com/vmware-tanzu/tanzu-framework/blob/main/apis/run/v1alpha3/clusterbootstraptemplate_types.go#L21-L29. They are,

- CNI
- CSI
- CPI
- Kapp
- AdditionalPackages

Since CSI and CPI are only used in vSphere, I will not include them for these AWS integration tests.

As for AdditionalPackages, I think it would be sufficient to test that these additional packages are successfully deployed:

```
additionalPackages:
  - refName: metrics-server.tanzu.vmware.com.0.5.1+vmware.1-tkg.2-zshippable
  - refName: secretgen-controller.tanzu.vmware.com.0.8.0+vmware.1-tkg.1-zshippable
  - refName: pinniped.tanzu.vmware.com.0.12.1+vmware.1-tkg.1-zshippable
 ```

Use the test https://github.com/vmware-tanzu/tanzu-framework/blob/package-based-lcm/pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_suite_test.go as an example to go off of.

Use the library created from #2388 to iterate through addons and verify they were installed correctly.
