### ISSUE TITLE
Modularize Kube-VIP config to a config-map

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/tanzu-framework#2533]
**Bug description**

Kube VIP hardcodes the launch data, including the network interface:

```
#@ def kube_vip_pod():
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: cp_enable
      value: "true"
    - name: vip_arp
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: address
      value: #@ data.values.VSPHERE_CONTROL_PLANE_ENDPOINT
    #@ if (not data.values.AVI_CONTROL_PLANE_HA_PROVIDER) and data.values.CLUSTER_API_SERVER_PORT:
    - name: port
      value: #@ "{}".format(data.values.CLUSTER_API_SERVER_PORT)
    #@ end
    - name: vip_interface
      value:  #@ data.values.VIP_NETWORK_INTERFACE

```
This defies the ability to be configured, bc you cant change the configuration of a pod after its already running... 

*Thought* 

To solve config of kube vip i think we may want to split it into a Deployment or  ConfigMap if hot reloads work...  i.e. the kube vip docs say you can do something like this :

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  cidr-default: 192.168.0.200/29                      # CIDR-based IP range for use in the default Namespace
  range-development: 192.168.0.210-192.168.0.219      # Range-based IP range for use in the development Namespace
  cidr-finance: 192.168.0.220/29,192.168.0.230/29     # Multiple CIDR-based ranges for use in the finance Namespace
  cidr-global: 192.168.0.240/29    
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ x ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

kube vip would be fully configuratble from the interface perspective for people trying to do advanced networking, antrea IPAM and so on

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
