### ISSUE TITLE
value ref is not cloned for additional packages in ClusterBootstrap object

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#2585]
**Bug description**
value ref is not cloned for additional packages
For example, when we specify pinniped* in additionalpackages, default webhook should populate the package with secret as per tkr specified
```
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: ClusterBootstrap
metadata:
  annotations:
    tkg.tanzu.vmware.com/add-missing-fields-from-tkr: v1.23.5---vmware.1-tkg.1
  name: abc124
  namespace: tkg-system
spec:
  additionalPackages:
  - refName: metrics-server*
  - refName: secretgen-controller*
  - refName: pinniped*
  ```

ClusterBootstrap Resource as populated by webhook:
```
spec:
    additionalPackages:
    - refName: metrics-server.tanzu.vmware.com.0.5.1+vmware.1-tkg.2-zshippable
    - refName: secretgen-controller.tanzu.vmware.com.0.8.0+vmware.1-tkg.1-zshippable
    - refName: pinniped.tanzu.vmware.com.0.12.1+vmware.1-tkg.1-zshippable
 ```
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
