### ISSUE TITLE
Use a specially labeled ConfigMap to mark additional TKRs as compatible

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#2592]
### Describe the feature request

In addition to what it is doing now, TKR Source Controller should also consider ConfigMaps labeled with (the new label) `run.tanzu.vmware.com/additional-compatible-tkrs: ""` to mark TKRs with versions listed in such ConfigMaps as Compatible=True.

Such ConfigMaps would be useful for at least two use cases: 
1. For TKG upgrade: to mark a specific TKR, to which the TKG Management Cluster would be upgraded, as compatible.
2. For cluster administrators to "bless" custom built TKRs as compatible.

Here's an example of such ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tkr-metadata
  namespace: tkg-system
  labels:
    run.tanzu.vmware.com/additional-compatible-tkrs: ""
data:
  tkrVersions: |
    - v1.23.6+vmware.1-tkg.1
    - v1.22.9+vmware.1-foo.2
    - v1.21.12+vmware.1-bar.2
```

### Affected product area (please put an X in all that apply)

- [X] APIs
- [ ] Addons
- [ ] CLI
- [X] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience
