### ISSUE TITLE
Install additional-compatible-tkr related config map when creating/upgrading management-cluster

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#2597]
**Describe the feature request**

In conjunction to #2592, when creating management-cluster with `package-based-lcm` feature-flag enabled, we need to create a config map in the bootstrap as well and management-cluster to mark a specific TKR compatible that will be used for management-cluster creation and upgrade.

For this, we can create this ConfigMap as part of TKG composite package deployment and update the configMap during the management-package upgrade when upgrading the management-cluster to newer version.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tkr-metadata
  namespace: tkg-system
  labels:
    run.tanzu.vmware.com/additional-compatible-tkrs: ""
data:
  tkrVersions: |
    - v1.23.6+vmware.1-tkg.1
```

The version of the TKR to specify here will be determined from the default BoM file and will be passed as a dataValue to the TKG composite package.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**
