### ISSUE TITLE
ConfigAPI objects are not cloned so it throws an error

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#2603]
**Bug description**
The ConfigAPI objects are not cloned so it throws an error. For example, Kappconfig
Error:
`
The ClusterBootstrap "abc124" is invalid: spec.kapp.valuesFrom.ProviderRef: Invalid value: v1.TypedLocalObjectReference{APIGroup:(*string)(0xc0018a1e20), Kind:"KappControllerConfig", Name:"v1.23.5---vmware.1-tkg.1"}: kappcontrollerconfigs.run.tanzu.vmware.com "v1.23.5---vmware.1-tkg.1" not found`

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by shivaani0505** [comment]
As of now lets' say if we dont specify kapp under spec, it doesn't config doesn't get cloned as default behaviour.
It was mentioned to me that we dont need to explicitly specify the core packages, and that the necessary packages would be picked up by default 
```
spec:
  kapp:
    refName: kapp-controller.tanzu.vmware.com
    valuesFrom:
      providerRef:
        apiGroup: run.tanzu.vmware.com
        kind: KappControllerConfig
        name: abc124
```
