### ISSUE TITLE
Antrea secret shows only data values which are true, false data values are not displayed

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#2663]
**Bug description**
Antrea secret shows only data values which are true, false data values are not displayed
```
➜  tanzu-framework git:(package-based-lcm) ✗ kubectl get secret mc-jun10-cluster-antrea-data-values -n tkg-system -o jsonpath='{.data.values\.yaml}' | base64 -d
infraProvider: aws
antrea:
    config:
        serviceCIDR: 100.64.0.0/13
        trafficEncapMode: encap
        tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
        featureGates:
            AntreaProxy: true
            EndpointSlice: true
            AntreaPolicy: true
            AntreaTraceflow: true
```            

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Behaviour shud be to display both true and false data values

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
