### ISSUE TITLE
Add PodSecurityPolicy support for capabilities package

### ISSUE THREAD

**Issue by rajathagasthya** [vmware-tanzu/tanzu-framework#2709]
**Bug description**

We have [host network](https://github.com/vmware-tanzu/tanzu-framework/blob/0045bd943758b77bb7eed35c3e34338cbd05fa86/packages/capabilities/bundle/config/values.yaml#L6) support for deploying capabilities package, but it does not support a cluster having PodSecurityPolicy. To support it, we need to provide a way for users to pass PSP names from values.yaml and pass it through to the capabilities controller's ClusterRole. 

Official documentation: https://kubernetes.io/docs/concepts/security/pod-security-policy/#via-rbac

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

Capabilities controller should support PSP.

**Steps to reproduce the bug**

Make sure a cluster has the following PSP:

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: example-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```

Try to deploy capabilities package. kube-apiserver does not create the deployment.

```
Events:
  Type     Reason        Age                    From                   Message
  ----     ------        ----                   ----                   -------
  Warning  FailedCreate  2m8s (x17 over 7m36s)  replicaset-controller  Error creating: pods "tanzu-capabilities-controller-manager-6dc7d64cc4-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
