### ISSUE TITLE
Allow dump sample data values for `tanzu package available get`

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#275]
(This is used to request new product features)

**Describe the feature request**

As an operator, I would like to see an example of data values in YAML format for a particular package, so that I could save that output into a values file to install a package by updating some of the configurations.

---

Here is an example  about what I would expect to see:

* `tanzu package available get contour.<domain>.com/1.15.1-tkg.1 --data-values`, it dumps a YAML output of data values to stdout.

```
namespace: projectcontour
contour:  
  configFileContents: {}  
  replicas: 2  
  useProxyProtocol: false  
  logLevel: info
envoy:  
  service:    
    type: LoadBalancer    
    externalTrafficPolicy: Local    
    annotations: {}    
    ...
certificates:  
  useCertManager: false  
  duration: 8760h  
  renewBefore: 360h  
  ...
...
```

* If a package does not have `valuesSchema` defined, then the `--data-values` flag needs to show a reasonable error/warning message to users.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**
