### ISSUE TITLE
`tanzu plugin list` returns a schema error

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/tanzu-framework#290]
**Bug description**

Running `tanzu plugin list` returns the following error:

```
mbp16 in /Users/nrb/projects/tanzu-framework (git) main
% tanzu plugin list
✖  could not decode config file: no kind "ClientConfig" is registered for version "config.tanzu.vmware.com/v1alpha1" in scheme "pkg/runtime/scheme.go:101"
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

A table of plugins and their versions to be output.

**Steps to reproduce the bug**

```bash
$ make build-install-cli-all
$ tanzu plugin list
$ ls -al ~/Library/Application\ Support/tanzu-cli  # to verify that the binaries weren't stale.
```

**Version** (include the SHA if the version is not obvious)

0684d9ff0264c4753f4e3ba762b13d1a45ae924e

**Environment where the bug was observed (cloud, OS, etc)**

macOS 10.15.7 (19H1323)

**Relevant Debug Output (Logs, manifests, etc)**

~/.tanzu/config.yaml:

```yaml
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli
        name: core
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg-plugins
        name: tkg
    unstableVersionSelector: experimental
current: tce-mgmt
kind: ClientConfig
metadata:
  creationTimestamp: null
servers:
- managementClusterOpts:
    context: tce-mgmt-admin@tce-mgmt
    path: /Users/nrb/.kube-tkg/config
  name: tce-mgmt
  type: managementcluster
```

~/.config/tanzu/config.yaml
```yaml
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli
        name: core
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg-plugins
        name: tkg
    unstableVersionSelector: experimental
current: tce-mgmt
kind: ClientConfig
metadata:
  creationTimestamp: null
servers:
- managementClusterOpts:
    context: tce-mgmt-admin@tce-mgmt
    path: /Users/nrb/.kube-tkg/config
  name: tce-mgmt
  type: managementcluster
```
