### ISSUE TITLE
Support air-gapped scenario for context-scoped plugins to allow registry override

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#2936]
**Describe the feature request**
Allow installation of context-scoped plugins with `tanzu plugin sync` when talking to management-cluster even if the CLIPlugin resources are pointing to different image registry.

- This can be done using a ConfigMap that tells tanzu cli on how to override the package repository.

Example:

- CLIPlugin resource deployed mentions `projects.registry.vmware.com/tkg` registry and user is using airgapped environment and has copied all images to the private registry `projects.registry.vmware.com/tkg`.

Admin needs to create below config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: context-plugin-repository-override
  namespace: tanzu-cli-system
  labels:
    cli.tanzu.vmware.com/cliplugin-image-repository-override: ""
data: 
  imageRepoMap: |- 
    projects.registry.vmware.com/tkg: projects-stg.registry.vmware.com/tkg/sandbox
```
- ConfigMap to used to specify this image repository override MUST contain label `cli.tanzu.vmware.com/cliplugin-image-repository-override` 
- ConfigMap MUST be created in `tanzu-cli-public` namespace and with any name.
- We need to make sure that all logged in users can read this config map.
- Tanzu CLI can read this configmap and while downloading context-scoped plugins it can update the references accordingly

**Describe alternatives you've considered**
None

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**
