### ISSUE TITLE
Plugin specific configuration like `BOMRepo` and `CompatibilityFilePath` should not be part of `ClientConfig` API

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#3149]
**Bug description**

Currently, ClientConfig API is used to store core tanzu configuration at `~/.config/tanzu/config.yaml`  However, there are few configurations like `bomRepo` and `compatibilityFilePath` was also added to this API as part of #1605 which is more for specific plugins and has nothing to do with the core tanzu CLI.

```
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    bomRepo: projects.registry.vmware.com/tce
    compatibilityFilePath: tkg-compatibility
```

We should remove this configuration from the `ClientConfig` API and put it to plugin specific configuration file.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

Remove plugin specific configuration like `BOMRepo` and `CompatibilityFilePath` from `ClientConfig` API

**Steps to reproduce the bug**
N/A

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
