### ISSUE TITLE
Context is not set according to the current environment.

### ISSUE THREAD

**Issue by pgandigesang** [vmware-tanzu/tanzu-framework#3661]
**Bug description**
The `contextType` under `discoverySources` in the Tanzu config file isnt being set according to the context the user is currently logged into. 

Currently logged into tmc context but the config file isnt updated to reflect the same information. 
```
 tanzu context list
  NAME  TYPE  ISMANAGEMENTCLUSTER  ISCURRENT  ENDPOINT                                   KUBECONFIGPATH  KUBECONTEXT
  test  tmc   false                true      <server>.vmware.com:443
```
Config:
```
tanzu config get
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    bomRepo: projects.registry.vmware.com/tkg
    compatibilityFilePath: tkg-compatibility
    discoverySources:
    - contextType: k8s
      local:
        name: default-local
        path: standalone
    edition: tkg
```

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (X) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (X) Plugin
- ( ) Security
- (X) Test and Release
- (X) User Experience
- ( ) Developer Experience

**Expected behavior**
It is expected that the config file reflect the same contextType that is being currently used.

**Steps to reproduce the bug**

1. `make build-install-cli-local`
2. `tanzu context create`
3. `tanzu config get`

**Version** (include the SHA if the version is not obvious)
```
❯ tanzu version
version: v0.25.0-dev
buildDate: 2022-10-13
sha: 1dfe1174
```
**Environment where the bug was observed (cloud, OS, etc)**
Darwin amd64

**Relevant Debug Output (Logs, manifests, etc)**
