### ISSUE TITLE
prodcc plan on vSphere spin out 3 md-0 workers for mgmt cluster

### ISSUE THREAD

**Issue by ydp** [vmware-tanzu/tanzu-framework#3701]
**Bug description**

prodcc plan on vSphere spin out 3 md-0 worker, the template looks like:
```
    workers:
      machineDeployments:
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-0
        replicas: 3
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-1
        replicas: null
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-2
        replicas: null
```
I added some log in init.go, and print out 3 variables:
the code is added right after control plane available:
```
	count, count0, count1, count2 := "-1", "-1", "-1", "-1"
	count, _ = c.TKGConfigReaderWriter().Get(constants.ConfigVariableWorkerMachineCount)
	count0, _ = c.TKGConfigReaderWriter().Get(constants.ConfigVariableWorkerMachineCount0)
	count1, _ = c.TKGConfigReaderWriter().Get(constants.ConfigVariableWorkerMachineCount1)
	count2, _ = c.TKGConfigReaderWriter().Get(constants.ConfigVariableWorkerMachineCount2)
	log.Infof("worker count: %s, count_0: %s, count_1: %s, count_2: %s", count, count0, count1, count2)
```
the output:
```
worker count: 3, count_0: 3, count_1: , count_2:
```

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (*) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Expected only has one md-0 worker node. Just like the legacy mode cluster:
```
kubo@cPgfRzjHTHpSU:~$ tanzu mc get
  NAME         NAMESPACE   STATUS   CONTROLPLANE  WORKERS  KUBERNETES        ROLES       PLAN
  tkg-mgmt-vc  tkg-system  running  3/3           3/3      v1.22.5+vmware.1  management  prod


Details:

NAME                                                            READY  SEVERITY  REASON  SINCE  MESSAGE
/tkg-mgmt-vc                                                    True                     109m
├─ClusterInfrastructure - VSphereCluster/tkg-mgmt-vc            True                     109m
├─ControlPlane - KubeadmControlPlane/tkg-mgmt-vc-control-plane  True                     109m
│ └─3 Machines...                                               True                     109m   See tkg-mgmt-vc-control-plane-94dfk, tkg-mgmt-vc-control-plane-f88vj, ...
└─Workers
  ├─MachineDeployment/tkg-mgmt-vc-md-0                          True                     109m
  │ └─Machine/tkg-mgmt-vc-md-0-78fcb9555f-2542p                 True                     109m
  ├─MachineDeployment/tkg-mgmt-vc-md-1                          True                     109m
  │ └─Machine/tkg-mgmt-vc-md-1-5c885c7465-xx6x9                 True                     109m
  └─MachineDeployment/tkg-mgmt-vc-md-2                          True                     109m
    └─Machine/tkg-mgmt-vc-md-2-6845f7fc6f-vctrq                 True                     109m


Providers:

  NAMESPACE                          NAME                    TYPE                    PROVIDERNAME  VERSION  WATCHNAMESPACE
  capi-kubeadm-bootstrap-system      bootstrap-kubeadm       BootstrapProvider       kubeadm       v1.0.1
  capi-kubeadm-control-plane-system  control-plane-kubeadm   ControlPlaneProvider    kubeadm       v1.0.1
  capi-system                        cluster-api             CoreProvider            cluster-api   v1.0.1
  capv-system                        infrastructure-vsphere  InfrastructureProvider  vsphere       v1.0.2
```

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
