### ISSUE TITLE
proxy variables in CC is not constructed in correct structure

### ISSUE THREAD

**Issue by lubronzhan** [vmware-tanzu/tanzu-framework#3869]
**Bug description**
The current expected proxy struct in CC variables is 
```
      - name: trust
        value:
          additionalTrustedCAs:
            - name: CompanyInternalCA-1
              data: aGVsbG8=
            - name: CompanyInternalCA-2
              data: bHWtcH9=
```
The `config_variable_association.star` file is not rendering it correctly
**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Cluster creation succeeded
**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**
