### ISSUE TITLE
MachineDeployment customizations with nested arrays, fail , due to ProcessYamlObjectArrayInterfaceType.

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/tanzu-framework#4526]
In the MachineDeployment customizations, we parse incoming cluster objects, which look something like this:

```
    workers:
      machineDeployments:
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=ubuntu
        name: md-0
        replicas: 1
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=ubuntu
        name: md-1-gpu
        replicas: 1
        variables:
          overrides:
          - name: worker
            value:
              count: 1
              machine:
                customVMXKeys:
                  pciPassthru.64bitMMIOSizeGB: "16"
                  pciPassthru.RelaxACSforP2P: "true"
                  pciPassthru.allowP2P: "true"
                  pciPassthru.use64bitMMIO: "true"
                diskGiB: 300
                memoryMiB: 16384
                numCPUs: 4
                hardwareVersion: vmx-17
```
The above code works fine, but if we add another map, which has an array in it `map[string]interface .....
```
                devices:
                - deviceId: 1234 <-- this fails
                  vendorId: 6789
```

It fails.  Thats because it appears we dont parse nested lists.  In the linked PR ive attached a PR that reproduces this, so it can be easy to fix now.
