### ISSUE TITLE
Move edition detection into configuration file (away from build-time flag)

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/tanzu-framework#569]
**Describe the feature request**

Today, we use `BUILD_EDITION` as an [LDFLAG](https://github.com/vmware-tanzu/tanzu-framework/blob/905b9a665918f3e2b2fd4ab2ed4f124a9e34c928/Makefile#L103) to determine things like:

* Whether we present the TCE kickstart UI / standard kickstart UI
* Defaults (such as CEIP settings)

Near term, we need to continue detection of editions inside of plugins such as `management-cluster`, however, we need to move away from this happening at build time, for the following reasons:

* We need interoperability between tanzu-* and tanzu-community-edition
* TCE should be using Tanzu Framework's published binaries and **not** re-building them from source.

🌟 **Proposal** 🌟

Let's move away from LDFLAGs and add a field to the [CLIOptions struct](https://github.com/vmware-tanzu/tanzu-framework/blob/905b9a665918f3e2b2fd4ab2ed4f124a9e34c928/apis/config/v1alpha1/clientconfig_types.go#L93-L99) that specifies the edition being used.

```go
// CLIOptions are options for the CLI.
type CLIOptions struct {
	// Repositories are the plugin repositories.
	Repositories []PluginRepository `json:"repositories,omitempty" yaml:"repositories"`
	// Edition of tanzu that is being run (e.g. community, standard, advanced).
	Edition string `json:"edition,omitempty" yaml:"edition"`
	// UnstableVersionSelector determined which version tags are allowed
	UnstableVersionSelector VersionSelectorLevel `json:"unstableVersionSelector,omitempty" yaml:"unstableVersionSelector"`
}
```

This would produce a configuration file client-side, that looks as follows (`cat ~/.config/tanzu/config.yaml`).

```yaml
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli
        name: core
    - gcpPluginRepository:
        bucketName: tce-cli-plugins
        name: tce
        rootPath: artifacts
    unstableVersionSelector: none
    edition: community
kind: ClientConfig
metadata:
  creationTimestamp: null
```

**Describe alternatives you've considered**

none

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

none
