### ISSUE TITLE
version prefix matching should be changed to exact match when updating TKR compatibility condition

### ISSUE THREAD

**Issue by prkalle** [vmware-tanzu/tanzu-framework#578]
**Bug description**
Currently the compatibility condition of the TKRs is updated by using a prefix matching of the management cluster version with the list of `managementClusterVersions` list in BOM compatibility metadata. However it only selects the _last_ managementClusterVersion that satisfies the prefix matching with management cluster version. 

An example tkr-compatiblity file that could cause issue is as shown below
```
version: v5
managementClusterVersions:
- version: v1.3.1-fips.1
  supportedKubernetesVersions:
  - v1.20.5+vmware.2-fips.1-tkg.1
- version: v1.3.1
  supportedKubernetesVersions:
  - v1.19.8+vmware.3-tkg.1
  - v1.20.5+vmware.2-tkg.1
  - v1.18.17+vmware.2-tkg.1
  - v1.20.4+vmware.3-tkg.1
  - v1.19.9+vmware.2-tkg.1
  - v1.18.16+vmware.3-tkg.1
  - v1.17.16+vmware.3-tkg.1
```

If the management cluster version is `v1.3.1-fips.1` the ideal match should be the first match.  But the current implementation only matches the last prefix match (it would match with v1.3.1) which would cause incorrect TKR compatibility conditions.
We should update the prefix matching to exact match unless we uncover any usecases.

There is another issue [#452](https://github.com/vmware-tanzu/tanzu-framework/issues/452) already filed relavent to this. But this issue is filed to see if we can update the version prefix match to exact match.
