### ISSUE TITLE
New NodePools inherit arbitrary KubeadmConfigTemplates

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/tanzu-framework#624]
**Bug description**

New NodePools borrow KubeadmConfigTemplate from other machinedeployments which, almost by definition is what we dont want to do .

 we grab the first element of the list of all MachineDeployments, as the basis for the kubeadmConfigTemplate for any node... 

Can we instead, specify the base template by name? or have another more flexible solution. 
```
	workers, err := clusterClient.GetMDObjectForCluster(options.ClusterName, options.Namespace)
	if err != nil || len(workers) == 0 {
		return errors.Wrap(err, "unable to get worker machine deployments")
	}

	baseWorker := workers[0]
	update := false
```

**Affected product area (please put an X in all that apply)**

**Expected behavior**

We can configure KubeadmConfigTemplates to align with custom node pool requirements in a user specified manner .

**Steps to reproduce the bug**

1) Make a windows cluster
2) add a linux nodepool 
```
name: linux-node-pool
replicas: 1
labels:
  key1: windows-ad
vsphere:
  memoryMiB: 8000
  diskGiB: 160
  numCPUs: 4
  datacenter: dc0
  datastore: sharedVmfs-0
  folder: folder0
  resourcePool: rp0
  vcIP: 10.161.147.191
  template: linux-ubuntu
  network: "VM Network"
```

** Potential Fix **

We could add a string for the kubeadmConfigTemplate name... i think that would be sufficient, then we could just skip the `workers[0]` thing in cases where this field is populated  
```
type NodePool struct {
	Name            string            `yaml:"name"`
	Replicas        *int32            `yaml:"replicas,omitempty"`
	AZ              string            `yaml:"az,omitempty"`
	NodeMachineType string            `yaml:"nodeMachineType,omitempty"`
	Labels          map[string]string `yaml:"labels,omitempty"`
	VSphere         VSphereNodePool   `yaml:"vsphere,omitempty"`
+	KubeadmConfigTemplateName string 
}
``` 

**Version** (include the SHA if the version is not obvious)
