### ISSUE TITLE
Capability CRD's GVR query should allow empty API group

### ISSUE THREAD

**Issue by rajathagasthya** [vmware-tanzu/tanzu-framework#882]
**Bug description**

Currently, GVR query in the `Capability` CRD has the `group` field as required with a minimum length of 1. This does not allow users to query for core k8s resources as they don't have an API group. The CRD needs to be changed to make this field optional.

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

GVR query allows a GVR check with no group specified.

**Steps to reproduce the bug**

Create Capability CRD to query for a core k8s resource such as `pods`:

```
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: Capability
metadata:
  name: capability-sample
spec:
  queries:
    - name: "q1"
      groupVersionResources:
        - name: "fooGVR"
          group: ""
          versions:
            - v1
          resource: "pods"
```

The CRD's openAPI schema does not allow this resource to be created:

```
The Capability "capability-sample" is invalid: spec.queries.groupVersionResources.group: Invalid value: "": spec.queries.groupVersionResources.group in body should be at least 1 chars long
```
